Update Graylog implementation
PowerRhino/rocksteady pull request #45
Opened 2021-04-12 07:56 UTC by octopusinvitro

Graylog has been updated to version 4. In Graylog 4, user permissions for stream access are not granted through roles anymore. If we create a new stream and want all users to access it, we have to share the stream with all users one by one.

Hence, the Graylog implementation in Rocksteady needs to be updated to reflect these changes otherwise we won’t be able to create Rocksteady apps when they need an associated Graylog stream. This is because in the implementation it was made mandatory that both creation of the stream and the app succeed.

## Summary of changes:

* Refactor. There was a bit of convoluted complexity and repeated conditional logic. Since I have to touch many classes to update the implementation, it is a good moment to refactor them first. The first commits (starting with `Cleanup:`) are for refactoring this logic to a place where adding the Graylog update is easy to implement and reason about. The commits starting with `Graylog:` are the implementation.

* Improving the lack of test coverage uncovered a bug in which we are not returning JSON in the JSON endpoints which threw JSON parsing errors when testing and can be surprising for someone consuming the API. To make the API a bit more
consistent I am returning:

  { app: X } on success and
  { error: X } on failure

everywhere. We can improve this design in the future. The [Rocksteady API](doc/rocksteady_api.md) and the [Graylog implementation](doc/graylog_implementation.md) have been documented inside of the `doc` folder.

* Another bug due to lack of test coverage was, not being able to display the index page on deletion error. This is because it redirects to the index, which needs the variable @repos, so the page was exploding. This was fixed by setting the @repos variable before redirecting to the index.

* The form was updated to simplify the logic and make it a bit easier to reason about. Also some things were incorrect, for example the `for` attribute in HTML labels is supposed to point to the input it refers to. Also, there is no need for these labels to have different copy for "new" and "update" scenarios, no other labels do that. Finally, the copy of the help text was updated. For example, a person creating an app doesn't necessarily need to know about the details of the Graylog API like what is an index set id.

![graylog](https://user-images.githubusercontent.com/2157089/114360243-b7f51e80-9b6c-11eb-895e-74bca757de18.png)

* Remove the feature to turn Graylog ON/OFF. Removing the `GRAYLOG_ENABLED` environment variable and the logic associated with it simplifies code, writing tests and testing on staging and live. If someone wanted to create apps with no Graylog stream they can still do it by just not ticking the Graylog checkbox in the web interface (or not sending `with_stream` with a value of `'1'` when using Rocksteady's JSON API).

2021-04-13 08:48 UTC, Gabbendorf commented on spec/services/graylog_api/altmetric_users_spec.rb
> +      end
You could say that this is already tested in line 9, unless you treat this as a more explicit piece of documentation about the check on the altmetric emails?

2021-04-13 09:02 UTC, Gabbendorf commented
LGTM 😊.
I left a tiny comment. Also, since it is my understanding that BotsAndUs are not using Rocksteady anymore, we can update the README at the very beginning when it gives an overview of the product, right?

2021-04-13 11:23 UTC, octopusinvitro commented on app/services/graylog_api/altmetric_users.rb
> +    end
Now that I think about it, this should be handled differently, and make it more generic

2021-04-13 17:44 UTC, octopusinvitro commented on spec/services/graylog_api/altmetric_users_spec.rb
> +      end
It was indeed an explicit piece of documentation but I am also testing the `$` at the end of the regex. Although on second though I think we should generalize this part of the code to remove the reference to Altmetric and Altmetric emails

2021-04-19 09:16 UTC, octopusinvitro commented on app/models/app_deletion.rb
> +  end
I wonder if this should be wrapped in a transaction so that either both things happen or none of them :thinking:

2021-04-19 09:21 UTC, octopusinvitro commented on doc/rocksteady_api.md
> +    "ERROR_NAME": "ERROR_MESSAGE",
Note to self: Remove these underscores :facepalm:

2021-04-19 11:07 UTC, epaune-alt requested changes
Very nice refactoring!

Dropped a few comments and questions.

2021-04-19 11:09 UTC, epaune-alt commented on app/models/app_deletion.rb
> +  end
But `app.destroy` is the only one that is calling the DB, isn't it?

2021-04-19 11:09 UTC, epaune-alt commented on app/services/graylog_api/altmetric_users.rb
> +    end
Yes, I agree...

2021-04-19 11:29 UTC, octopusinvitro commented on app/models/app_deletion.rb
> +  end
yep but if you can't destroy the app you shouldn't call delete on Nomad and viceversa, nope?
otherwise one would be deleted and the other one would be hanging :thinking: 
what do you think

2021-04-19 11:37 UTC, epaune-alt commented on app/models/app_deletion.rb
> +  end
Ahh, yes, you are right:
```ruby
app.transaction do
  app.destroy!

  nomad_deletion = HTTP.delete(url).status.success?
  raise ActiverRecord::Rollback unless nomad_deletion
  true
end
```

2021-04-19 11:39 UTC, octopusinvitro commented on spec/services/graylog_api/stream_spec.rb
> +    it 'does not create stream if id is provided' do
Ah, I am documenting two different things here:
* The previous test is telling us that the presence of an index set id is mandatory in order to create a stream. 
* The second one is preventing us from passing an id to the `create` method, because you are not supposed to pass an id to `create`, but it is mandatory in `update`.

It's not clear at all from the tests, so I'll rework them :+1: (I don't know why I am passing `title: nil` in the previous one :thinking: )

2021-04-19 12:14 UTC, octopusinvitro commented on app/models/app_update.rb
> +  def create_stream?
we only have `stream_config` if the app has a stream already or we are adding a stream to a new or existing app.

this is the update method so we won't be creating apps from scratch.

if we have an existing app with no stream (`app.graylog_stream.blank`) and we are updating it to add a stream (`stream_config` is present) changing the value of the `repository_name` just means the stream will be created with the new value of `repository_name`. We will indeed call update stream later, so we could return on create to avoid two requests:

```ruby
    return create_graylog_stream if create_stream?
    update_graylog_stream if update_stream?
```

2021-04-19 12:20 UTC, octopusinvitro commented on spec/models/app_update_spec.rb
> +        app
This test is for apps with a stream, so `app` is an app created with a stream.
When we create the app, we create a stream, changing the stream count in the database.

If we don't create the app first, it will count against this check:

```ruby
expect { app_update.update(params) }.to_not change(GraylogStream, :count)
```

I want to test that _the call to update_ doesn't change the stream count.

2021-04-19 12:21 UTC, epaune-alt commented on app/models/app_update.rb
> +  def create_stream?
Yes, this seems sensible

2021-04-19 12:27 UTC, epaune-alt commented on spec/models/app_update_spec.rb
> +        app
Can we use then `let!` in line https://github.com/PowerRhino/rocksteady/pull/45/files/a3b6a399c56820019950fa0ff3a0adf6925b47e1..d123bc9a51ea25309d89b83975483a799a525ff4#diff-da0787d274bc5ee93c172cc0fa79d3cd1f3a7e5ba8c3ff862d83a5b06dac16ddR116 ?
I cannot test it myself because `bundle install` fails because of the `mimemagic` issue...

2021-04-19 12:40 UTC, octopusinvitro commented on Gemfile.lock
> +  rails-controller-testing (~> 1.0)
I'm old :older_woman:

what do you youngsters use these days instead of `assigns` and `assert_template`? :smile:

2021-04-19 12:43 UTC, octopusinvitro commented on spec/models/app_update_spec.rb
> +        app
oh nice, didn't know about `let!` :+1:

2021-04-19 13:58 UTC, epaune-alt commented on Gemfile.lock
> +  rails-controller-testing (~> 1.0)
Checking `assigns` or `assert_template` is checking implementation details. I'd check that something specific about the view is being displayed.

Or if we don't have any logic in place to select the view that is shown, checking that a successful response is returned might be enough.

2021-04-20 11:51 UTC, octopusinvitro commented on spec/services/graylog_api/altmetric_users_spec.rb
> +      it 'ignores users that throw an E11000 duplicate key error collection' do
:+1: 
I left a small reference to the error, in case we get it in the future we know where it comes from

2021-04-20 11:53 UTC, octopusinvitro commented on spec/services/graylog_api/shares_spec.rb
> +    def shares_body
I renamed it but moved it inside of the test because that's the only place where it's used and it was a mistake to put it outside to beging with :+1:

2021-04-20 16:17 UTC, octopusinvitro commented on spec/services/graylog_api/success_response_spec.rb
> +    response = success_response(foo: { bar: { qux: 42 } })
would you prefer I pass JSON instead? :thinking: 
```ruby
response = success_response('"foo": { "bar": { "qux": 42 } }')
```
I didn't find it confusing because that is how factory bot works too:
```ruby
FactoryBot(:factory_name, foo: 'bar')
```

2021-04-20 16:21 UTC, octopusinvitro commented on spec/services/graylog_api/success_response_spec.rb
> -  describe '#body' do
Nothing! :smile: 
It's back :+1: 

(It was just such a simple test that so much indentation seemed too much in my brain)

2021-04-20 16:49 UTC, octopusinvitro commented on spec/controllers/apps_controller_spec.rb
> +  def job_spec
Because it's not relevant for any of the tests, it's just something we have to pass to the app.
We could just pass `job_spec: 'job {}` to the app and it would work, actually.
We could also read the `nomad_job.hcl` file in the root directory and pass that.

I think the only reason this job spec exist in this test is to document the structure, but I think having the `nomad_job.hcl` is probably enough (and it's mentioned in the README) so I'd be happy to just pass `job_spec: 'job {}'` to the app and get rid of the method :thinking: 
what do you think

2021-04-21 05:49 UTC, epaune-alt commented on spec/services/graylog_api/success_response_spec.rb
> +    response = success_response(foo: { bar: { qux: 42 } })
Yes, in this case I think it would be better.

2021-04-21 05:50 UTC, epaune-alt commented on spec/controllers/apps_controller_spec.rb
> +  def job_spec
Yes, you are right.

2021-04-21 05:57 UTC, epaune-alt commented on spec/models/app_update_spec.rb
> +    app.save
🤔  We are testing `update`, so we start with a persisted `app`, and then we try to update it. 

Looking again at you comment, it looks like you were working too late! This is the test, not the code 😄

2021-04-21 08:50 UTC, octopusinvitro commented on spec/models/app_update_spec.rb
> +    app.save
true! :facepalm: 
added

2021-04-21 11:09 UTC, epaune-alt requested changes
Just a few dangling threads to address

2021-04-21 11:10 UTC, epaune-alt commented on app/models/app_deletion.rb
> +    end
Or `nil`, to keep the current behaviour

2021-04-21 13:52 UTC, octopusinvitro commented on app/models/app_deletion.rb
> +      raise ActiveRecord::Rollback
nope, it didn't! :smile: 
the tests were exploding, that's why I had to add this

2021-04-21 13:56 UTC, octopusinvitro commented on app/models/app_deletion.rb
> +    end
yep, 
we made it so that if the app can't be destroyed, nil will be returned, 
and if nomad can't be destroyed, it will return nil as well. 
you can see it in the tests :+1:

2021-04-21 13:57 UTC, octopusinvitro commented on spec/services/graylog_api/stream_spec.rb
> +    it 'does not create stream if steam id is provided' do
:smile: 
I really need to open Steam and play some games :video_game:

2021-04-22 06:00 UTC, epaune-alt commented on app/models/app_deletion.rb
> +      raise ActiveRecord::Rollback
The transaction block will rescue an `ActiveRecord::Rollback` only. Any other exception will not be rescued.

The natural place for the `rescue` is outside the transaction block:
```ruby
def delete_from_database_and_nomad
  app.transaction do
    app.destroy!
    fail ActiveRecord::Rollback unless successful_nomad_deletion?

    true
  end
rescue ActiveRecord::RecordNotDestroyed
  nil
end
```
If you are not convinced, comment the lines in the tests with `app.define_singleton_method(:destroy) do false end` and add a `raise  ActiveRecord::RecordNotDestroyed` after `app.destroy!`: the tests for database failure will pass.

2021-04-23 05:45 UTC, epaune-alt approved these changes

2021-05-06 11:06 UTC, merged